# Foundry Configuration File
# Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

# The Default Profile
[profile.default]
solc_version = "0.8.28"
evm_version = "prague"
auto_detect_solc = false
optimizer = true
optimizer_runs = 1000
via_ir = true
gas_limit = 1_000_000_000 # ETH is 30M, but we use a higher value.
always_use_create_2_factory = true
remappings = [
  "murky=lib/murky",
  "dn404/=lib/dn404/src",
  "solady=lib/solady/src"
]

[fmt]
line_length = 100 # While we allow up to 120, we lint at 100 for readability.

[profile.default.fuzz]
runs = 256

[invariant]
runs = 30
depth = 15
fail_on_revert = true
dictionary_weight = 80
